version: "2.3"

services:
    redis:
      container_name: service-redis
      image: redis:bookworm
      ports:
        - 6379
      command: redis-server --save 60 1 --loglevel warning --requirepass password
      volumes:
        - ./.rdata:/data
      networks:
        - redis

    postgres:
        container_name: service-postgres
        image: postgres:12
        environment:
          - POSTGRES_DB=auth_service_db_1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
        ports:
          - 5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    auth_service-container:
        image: ghcr.io/userver-framework/ubuntu-userver-build-base:v1
        privileged: true
        environment:
          - POSTGRES_DB=auth_service_db_1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CC
          - CCACHE_DIR=/auth_service/.ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/cores
          - CXX
          - MAKE_OPTS
          - CMAKE_COMMON_FLAGS
        volumes:
          - .:/auth_service:rw
          - ./third_party/userver/tools/docker:/tools:ro
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /auth_service
        entrypoint:
          - /tools/run_as_user.sh
        depends_on:
          - postgres
          - redis
        networks:
          - postgres
          - redis

networks:
    postgres:
        driver: bridge
    redis:
        driver: bridge
