worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: false

server-port: 8080

secdist-path: /etc/authentification_service/secure_data.json

dbconnection: 'postgresql://user:password@service-postgres:5432/authentification_service_db_1'
